version: 2
updates:
  # Root directory Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"