# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 3 * * 0'   # UTC 日曜 12:00 JST

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pip install ruff black isort pytest pytest-cov
      - run: ruff .
      - run: black --check .
      - run: isort --check-only .
      - run: pytest --cov=app --cov-report=xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml