# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日 09:00 JST (UTC 00:00)

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: コードフォーマットチェック
        run: black --check . --exclude="pyproject\.toml"
      - name: Lintチェック
        run: flake8 .
      - name: テスト実行とカバレッジ取得
        run: |
          if pytest -q --cov=. --cov-report=xml; then
            echo "Tests completed successfully"
          else
            echo "No tests found or tests failed"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
        if: success() || failure()